server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash
  base-url: https://generativelanguage.googleapis.com/v1beta
  timeout-seconds: 20
